/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.agendagastos;

import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fernando
 */
public class JFrameMain extends javax.swing.JFrame {

    String fecha, nombre, categoria, monto, descripcion;
    boolean validarCampos;
    DefaultTableModel modelo = new DefaultTableModel();
    DefaultTableCellRenderer cellRenderer = new DefaultTableCellRenderer();

    public JFrameMain() {
        initComponents();
        setTitle("Agenda de Gastos");
        setDefaultCloseOperation(JFrameMain.EXIT_ON_CLOSE);
        setSize(1261, 568);
        setLocationRelativeTo(null);
        setResizable(false);
        setVisible(true);
        modelo.addColumn("Fecha");
        modelo.addColumn("Nombre");
        modelo.addColumn("Categoria");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Monto (S/.)");
        jtableRegistros.setModel(modelo);
        jtableRegistros.setSize(800, 400);
        jtableRegistros.getColumnModel().getColumn(0).setPreferredWidth(100);
        jtableRegistros.getColumnModel().getColumn(0).setResizable(false);
        jtableRegistros.getColumnModel().getColumn(0).setHeaderRenderer(cellRenderer);
        jtableRegistros.getColumnModel().getColumn(0).setCellRenderer(cellRenderer);
        jtableRegistros.getColumnModel().getColumn(1).setPreferredWidth(250);
        jtableRegistros.getColumnModel().getColumn(1).setResizable(false);
        jtableRegistros.getColumnModel().getColumn(1).setHeaderRenderer(cellRenderer);
        jtableRegistros.getColumnModel().getColumn(1).setCellRenderer(cellRenderer);
        jtableRegistros.getColumnModel().getColumn(2).setPreferredWidth(150);
        jtableRegistros.getColumnModel().getColumn(2).setResizable(false);
        jtableRegistros.getColumnModel().getColumn(2).setHeaderRenderer(cellRenderer);
        jtableRegistros.getColumnModel().getColumn(2).setCellRenderer(cellRenderer);
        jtableRegistros.getColumnModel().getColumn(3).setPreferredWidth(400);
        jtableRegistros.getColumnModel().getColumn(3).setResizable(false);
        jtableRegistros.getColumnModel().getColumn(3).setHeaderRenderer(cellRenderer);
        jtableRegistros.getColumnModel().getColumn(3).setCellRenderer(cellRenderer);
        jtableRegistros.getColumnModel().getColumn(4).setPreferredWidth(90);
        jtableRegistros.getColumnModel().getColumn(4).setResizable(false);
        jtableRegistros.getColumnModel().getColumn(4).setHeaderRenderer(cellRenderer);
        jtableRegistros.getColumnModel().getColumn(4).setCellRenderer(cellRenderer);
        cellRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        jdateFecha.getDateEditor().setEnabled(false);
        txtTotal.setEditable(false);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        cmbCategoria = new javax.swing.JComboBox<>();
        txtMonto = new javax.swing.JTextField();
        jdateFecha = new com.toedter.calendar.JDateChooser();
        btnRegistrar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableRegistros = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel1.setText("Registro de Gastos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        jLabel2.setText("Nombre :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        jLabel3.setText("Categoria :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        jLabel4.setText("Descripcion :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        jLabel5.setText("Monto (S/.) :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        jLabel6.setText("Fecha :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        txtNombre.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 230, -1));

        cmbCategoria.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        cmbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alimentacion", "Salud", "Cuidado Personal", "Educacion", "Vivienda", "Entretenimiento", "Otros Gastos" }));
        getContentPane().add(cmbCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 230, -1));

        txtMonto.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        txtMonto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMontoKeyTyped(evt);
            }
        });
        getContentPane().add(txtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 230, -1));

        jdateFecha.setDateFormatString("yyyy-MM-dd");
        jdateFecha.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        getContentPane().add(jdateFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 230, -1));

        btnRegistrar.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 150, 50));

        txtDescripcion.setColumns(20);
        txtDescripcion.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        txtDescripcion.setLineWrap(true);
        txtDescripcion.setRows(5);
        txtDescripcion.setWrapStyleWord(true);
        txtDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescripcionKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(txtDescripcion);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 230, -1));

        jtableRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Nombre", "Categoria", "Descripcion", "Monto"
            }
        ));
        jScrollPane1.setViewportView(jtableRegistros);
        if (jtableRegistros.getColumnModel().getColumnCount() > 0) {
            jtableRegistros.getColumnModel().getColumn(0).setResizable(false);
            jtableRegistros.getColumnModel().getColumn(0).setPreferredWidth(50);
            jtableRegistros.getColumnModel().getColumn(1).setResizable(false);
            jtableRegistros.getColumnModel().getColumn(1).setPreferredWidth(100);
            jtableRegistros.getColumnModel().getColumn(2).setResizable(false);
            jtableRegistros.getColumnModel().getColumn(2).setPreferredWidth(70);
            jtableRegistros.getColumnModel().getColumn(3).setResizable(false);
            jtableRegistros.getColumnModel().getColumn(3).setPreferredWidth(150);
            jtableRegistros.getColumnModel().getColumn(4).setResizable(false);
            jtableRegistros.getColumnModel().getColumn(4).setPreferredWidth(50);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 760, -1));

        jLabel7.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel7.setText("TOTAL(S/.) :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 470, -1, 30));

        txtTotal.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 460, 120, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

        registrarDatos();
        validarCampos();
        registrarTabla();
        limpiarDatos();

    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed

    }//GEN-LAST:event_txtTotalActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped

        int key;
        boolean mayusculas, minusculas, espacio;

        key = evt.getKeyChar();

        mayusculas = key >= 65 && key <= 90;
        minusculas = key >= 97 && key <= 122;
        espacio = key == 32;

        if (!(minusculas || mayusculas || espacio)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtMontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontoKeyTyped
        // TODO add your handling code here:
        int key;
        boolean numeros, punto;

        key = evt.getKeyChar();
        numeros = key >= 48 && key <= 57;
        punto = key == 46;
        if (!(numeros || punto)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtMontoKeyTyped

    private void txtDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcionKeyTyped
        // TODO add your handling code here:
        int key;
        boolean mayusculas, minusculas, espacio;
        key = evt.getKeyChar();

        mayusculas = key >= 65 && key <= 90;
        minusculas = key >= 97 && key <= 122;
        espacio = key == 32;

        if (!(minusculas || mayusculas || espacio)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtDescripcionKeyTyped

    private void registrarDatos() {

        fecha = ((JTextField) jdateFecha.getDateEditor().getUiComponent()).getText();
        nombre = txtNombre.getText();
        categoria = cmbCategoria.getSelectedItem().toString();
        monto = txtMonto.getText();
        descripcion = txtDescripcion.getText();

    }

    private void registrarTabla() {

        double total = 0;

        if (validarCampos == false) {
            return;
        } else if (validarCampos == true) {
            String[] columnas = new String[5];
            columnas[0] = fecha;
            columnas[1] = nombre;
            columnas[2] = categoria;
            columnas[3] = descripcion;
            columnas[4] = monto;
            modelo.addRow(columnas);

            for (int i = 0; i < modelo.getRowCount(); i++) {
                total += Double.parseDouble(modelo.getValueAt(i, 4).toString());
            }
            txtTotal.setText(String.valueOf(total));
            txtTotal.setHorizontalAlignment(JTextField.CENTER);
            JOptionPane.showMessageDialog(null,"Registro guardado exitosamente");
        }

    }

    private void validarCampos() {
        if (fecha.equals("") || nombre.equals("") || descripcion.equals("") || monto.equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor completar todos los campos");
            validarCampos = false;

        } else {
            validarCampos = true;
        }

    }
    private void limpiarDatos(){
        jdateFecha.setDate(null);
        txtNombre.setText("");
        txtMonto.setText("");
        txtDescripcion.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cmbCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser jdateFecha;
    private javax.swing.JTable jtableRegistros;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
